- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: test description.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1016/j.csbj.2020.05.017
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: arxiv:1605.06409
  type: paper
  publisher: Neural Information Processing Systems (NIPS), 2016.
  image: images/1605.06409.png
  description: The 3-rd most influential paper in Neural Information Processing Systems (NIPS), 2016. Pytorch visual operator library.
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1605.06409
    - type: source
      text: Code
      link: https://github.com/daijifeng001/R-FCN

- id: arxiv:2010.04159
  type: paper
  publisher: International Conference on Learning Representations (ICLR), 2021.(Oral)
  image: images/2010.04159.png
  description: The 2-nd most influential paper in International Conference on Learning Representations (ICLR), 2021.
  buttons:
    - type: paper
      link: https://arxiv.org/abs/2010.04159
    - type: source
      text: Code
      link: https://github.com/fundamentalvision/Deformable-DETR

- id: arxiv:1703.06211
  type: paper
  publisher: International Conference on Computer Vision (ICCV), 2017. (Oral)
  image: images/1703.06211.png
  description: The 6-th most influential paper in International Conference on Computer Vision (ICCV), 2017. Pytorch visual operator library.
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1703.06211
    - type: source
      text: Code
      link: https://github.com/msracver/Deformable-ConvNets

- id: arxiv:2211.05778
  type: paper
  publisher: IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2023. (Highlight)
  image: images/2211.05778.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/2211.05778

- id: arxiv:1906.07155
  type: paper
  publisher: IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2019.
  image: images/1906.07155.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1906.07155
    - type: source
      text: Code
      link: https://github.com/open-mmlab/mmdetection

- id: arxiv:1512.04412
  type: paper
  publisher: IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2016. (Oral)
  image: images/1512.04412.png
  description: 1-st place winner of the COCO 2015 segmentation challenge. (0.36 sec/image test speed using VGG-16 net)
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1512.04412
    - type: source
      text: Code
      link: https://github.com/daijifeng001/MNC

- id: arxiv:1811.11168
  type: paper
  publisher: IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2019.
  image: images/1811.11168.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1811.11168
    - type: source
      text: Code
      link: https://github.com/msracver/Deformable-ConvNets

- id: arxiv:1711.11575
  type: paper
  publisher: IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2018. (Oral)
  image: images/1711.11575.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1711.11575
    - type: source
      text: Code
      link: https://github.com/msracver/Relation-Networks-for-Object-Detection

- id: arxiv:1611.07709
  type: paper
  publisher: IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2017. (Spotlight)
  image: images/1611.07709.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1611.07709
    - type: source
      text: Code
      link: https://github.com/msracver/FCIS

- id: arxiv:1503.01640
  type: paper
  publisher: International Conference on Computer Vision (ICCV), 2015.
  image: images/1503.01640.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1503.01640

- id: arxiv:1604.05144
  type: paper
  publisher: IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2016. (Oral)
  image: images/1604.05144.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1604.05144
    - type: source
      text: Code
      link: http://www.jifengdai.org/downloads/scribble_sup/

- id: arxiv:1611.07715
  type: paper
  publisher: IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2017.
  image: images/1611.07715.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1611.07715
    - type: source
      text: Code
      link: https://github.com/msracver/Deep-Feature-Flow

- id: arxiv:1703.10025
  type: paper
  publisher: International Conference on Computer Vision (ICCV), 2017.
  image: images/1703.10025.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1703.10025
    - type: source
      text: Code
      link: https://github.com/msracver/Flow-Guided-Feature-Aggregation

- id: arxiv:1412.1283
  type: paper
  publisher: IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2015.
  image: images/1412.1283.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1412.1283

- id: arxiv:1908.08530
  type: paper
  publisher: International Conference on Learning Representations (ICLR), 2020.
  image: images/1908.08530.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/1908.08530
    - type: source
      text: Code
      link: https://github.com/jackroos/VL-BERT

- id: arxiv:2112.01522
  type: paper
  publisher: IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2022.
  image: images/2112.01522.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/2112.01522
    - type: source
      text: Code
      link: https://github.com/fundamentalvision/Uni-Perceiver

- id: arxiv:2206.04674
  type: paper
  publisher: Neural Information Processing Systems (NIPS), 2022. (Spotlight)
  image: images/2206.04674.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/2206.04674
    - type: source
      text: Code
      link: https://github.com/fundamentalvision/Uni-Perceiver

- id: arxiv:2211.09808
  type: paper
  publisher: IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2023. (Highlight)
  image: images/2211.09808.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/2211.09808

- id: arxiv:2305.11175
  type: paper
  publisher: Arxiv Tech Report, 2023.
  image: images/2305.11175.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/2305.11175
    - type: source
      text: Code
      link: https://github.com/OpenGVLab/VisionLLM

- id: arxiv:2203.17270
  type: paper
  publisher: European Conference on Computer Vision (ECCV), 2022.
  image: images/2203.17270.png
  description: The 6-th most influential paper in European Conference on Computer Vision (ECCV), 2022. The 100 most cited AI papers of 2022. Automatic-driving competition Waymo 2022 champion.
  buttons:
    - type: paper
      link: https://arxiv.org/abs/2203.17270
    - type: source
      text: Code
      link: https://github.com/zhiqi-li/BEVFormer

- id: arxiv:2211.10439
  type: paper
  publisher: IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2023. (Highlight)
  image: images/2211.10439.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/2211.10439

- id: arxiv:2212.10156
  type: paper
  publisher: IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2023. (Best Paper Award)
  image: images/2212.10156.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/2212.10156
    - type: source
      text: Code
      link: https://github.com/opendrivelab/uniad

- id: arxiv:2305.17144
  type: paper
  publisher: Arxiv Tech Report, 2023.
  image: images/2305.17144.png
  buttons:
    - type: paper
      link: https://arxiv.org/abs/2305.17144
    - type: source
      text: Code
      link: https://github.com/OpenGVLab/GITM

- id: arxiv:2308.01907
  type: paper
  publisher: Arxiv Tech Report, 2023.
  buttons:
    - type: paper
      link: https://arxiv.org/abs/2308.01907
    - type: source
      text: Code
      link: https://github.com/opengvlab/all-seeing

- id: arxiv:2211.05781
